version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            set -o pipefail
            npm install || true
      - run:
          name: Run tests
          command: |
            set -o pipefail
            npm test || true

  test:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Run additional tests
          command: |
            set -o pipefail
            npm run additional-tests || true

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Nginx
          command: |
            sudo apt-get update
            sudo apt-get install -y nginx
      - run:
          name: Configure Nginx
          command: |
            sudo rm /etc/nginx/sites-enabled/default
            echo 'server {
              listen 84;
              root /var/www/html;
              index index.html;
              location / {
                try_files $uri $uri/ =404;
              }
            }' | sudo tee /etc/nginx/sites-available/default
      - run:
          name: Copy index.html to Nginx directory
          command: |
            sudo mkdir -p /var/www/html
            sudo cp index.html /var/www/html/
      - run:
          name: Start Nginx
          command: |
            sudo service nginx restart
            curl -I http://localhost:84 || true

workflows:
  version: 2
  build_deploy_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
