version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            set -o pipefail
            npm install || true
      - run:
          name: Run tests
          command: |
            set -o pipefail
            npm test || true

  test:
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - run:
          name: Run additional tests
          command: |
            set -o pipefail
            npm run additional-tests || true

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: |
            echo "Deploying application..."
            # Add your deployment commands here
            # Example:
            # ./deploy.sh
      - run:
          name: Start Application and Serve index.html on Port 84
          command: |
            echo "Starting application and serving index.html on port 84..."
            # Assuming you are using a simple HTTP server to serve index.html
            # Install a simple HTTP server if not already installed
            npm install -g http-server || true
            # Serve the index.html on port 84
            http-server -p 84 -c-1 || true

workflows:
  version: 2
  build_deploy_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
