version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8 # Using Python to serve the HTML file
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: |
            echo "Deploying index.html on localhost:85..."
            cd repo-folder # Navigate to the folder where your index.html is located
            python -m http.server 85

workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy
